/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_information             12
#define gattdb_manufacturer_name_string       14
#define gattdb_model_number_string            16
#define gattdb_hardware_revision_string       18
#define gattdb_firmware_revision_string       20
#define gattdb_system_id                      22
#define gattdb_pnp_id                         24
#define gattdb_human_interface_device         25
#define gattdb_hid_protocol_mode              27
#define gattdb_hid_report_map                 29
#define gattdb_hid_information                31
#define gattdb_hid_control_point              33
#define gattdb_hid_report                     35
#define gattdb_battery_service                38
#define gattdb_batt_level                     40
#define gattdb_phone_rx                       44
#define gattdb_phone_tx                       46

#define gattdb_generic_attribute_len          2
#define gattdb_service_changed_char_len       4
#define gattdb_database_hash_len              16
#define gattdb_client_support_features_len    1
#define gattdb_device_information_len         2
#define gattdb_manufacturer_name_string_len   12
#define gattdb_model_number_string_len        10
#define gattdb_hardware_revision_string_len   5
#define gattdb_firmware_revision_string_len   8
#define gattdb_system_id_len                  8
#define gattdb_pnp_id_len                     7
#define gattdb_human_interface_device_len     2
#define gattdb_hid_protocol_mode_len          1
#define gattdb_hid_report_map_len             23
#define gattdb_hid_information_len            4
#define gattdb_hid_control_point_len          1
#define gattdb_hid_report_len                 8
#define gattdb_battery_service_len            2
#define gattdb_batt_level_len                 1
#define gattdb_phone_rx_len                   255
#define gattdb_phone_tx_len                   255


#endif // __GATT_DB_H
